### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by mikel13200** [MegaMagnum/FiveM-WeatherSync#1]
should i put something like this on my server.cfg?
add_ace Weathersync.change allow

**Comment by MegaMagnum** [comment]
You should put it in a server.cfg like this:
`add_ace group.seniordeveloper Weathersync.change allow`

If you want it to be on the admin group or superadmin group just change seniordeveloper to the group name

**Comment by mikel13200** [comment]
thank you, appreaciate ur work <3
